// ─── CURRENCY DATA ────────────────────────────────────────────────────────────
// Shared across AddExpenseScreen and CreateTripSheet.
// toInrRate is a fallback — live rates from ExchangeRateService override it.
// ─────────────────────────────────────────────────────────────────────────────

class CurrencyEntry {
  const CurrencyEntry({
    required this.code,
    required this.name,
    required this.symbol,
    required this.flag,
    this.toInrRate = 1.0,
  });

  final String code;
  final String name;
  final String symbol;
  final String flag;
  final double toInrRate;
}

const List<CurrencyEntry> kAllCurrencies = [
  CurrencyEntry(code: 'AED', name: 'UAE Dirham',                symbol: 'د.إ',  flag: '🇦🇪', toInrRate: 22.6),
  CurrencyEntry(code: 'AFN', name: 'Afghan Afghani',            symbol: '؋',    flag: '🇦🇫', toInrRate: 0.90),
  CurrencyEntry(code: 'ALL', name: 'Albanian Lek',              symbol: 'L',    flag: '🇦🇱', toInrRate: 0.87),
  CurrencyEntry(code: 'AMD', name: 'Armenian Dram',             symbol: '֏',    flag: '🇦🇲', toInrRate: 0.21),
  CurrencyEntry(code: 'ARS', name: 'Argentine Peso',            symbol: '\$',   flag: '🇦🇷', toInrRate: 0.087),
  CurrencyEntry(code: 'AUD', name: 'Australian Dollar',         symbol: 'A\$',  flag: '🇦🇺', toInrRate: 53.5),
  CurrencyEntry(code: 'AZN', name: 'Azerbaijani Manat',         symbol: '₼',    flag: '🇦🇿', toInrRate: 49.1),
  CurrencyEntry(code: 'BAM', name: 'Bosnia-Herzegovina Mark',   symbol: 'KM',   flag: '🇧🇦', toInrRate: 46.1),
  CurrencyEntry(code: 'BBD', name: 'Barbadian Dollar',          symbol: '\$',   flag: '🇧🇧', toInrRate: 41.75),
  CurrencyEntry(code: 'BDT', name: 'Bangladeshi Taka',          symbol: '৳',    flag: '🇧🇩', toInrRate: 0.72),
  CurrencyEntry(code: 'BGN', name: 'Bulgarian Lev',             symbol: 'лв',   flag: '🇧🇬', toInrRate: 46.1),
  CurrencyEntry(code: 'BHD', name: 'Bahraini Dinar',            symbol: '.د.ب', flag: '🇧🇭', toInrRate: 221.5),
  CurrencyEntry(code: 'BIF', name: 'Burundian Franc',           symbol: 'Fr',   flag: '🇧🇮', toInrRate: 0.029),
  CurrencyEntry(code: 'BND', name: 'Brunei Dollar',             symbol: '\$',   flag: '🇧🇳', toInrRate: 62.4),
  CurrencyEntry(code: 'BOB', name: 'Bolivian Boliviano',        symbol: 'Bs.',  flag: '🇧🇴', toInrRate: 12.1),
  CurrencyEntry(code: 'BRL', name: 'Brazilian Real',            symbol: 'R\$',  flag: '🇧🇷', toInrRate: 15.3),
  CurrencyEntry(code: 'BSD', name: 'Bahamian Dollar',           symbol: '\$',   flag: '🇧🇸', toInrRate: 83.5),
  CurrencyEntry(code: 'BTN', name: 'Bhutanese Ngultrum',        symbol: 'Nu',   flag: '🇧🇹', toInrRate: 1.0),
  CurrencyEntry(code: 'BWP', name: 'Botswanan Pula',            symbol: 'P',    flag: '🇧🇼', toInrRate: 6.1),
  CurrencyEntry(code: 'BYN', name: 'Belarusian Ruble',          symbol: 'Br',   flag: '🇧🇾', toInrRate: 26.1),
  CurrencyEntry(code: 'BZD', name: 'Belize Dollar',             symbol: '\$',   flag: '🇧🇿', toInrRate: 41.4),
  CurrencyEntry(code: 'CAD', name: 'Canadian Dollar',           symbol: 'C\$',  flag: '🇨🇦', toInrRate: 61.7),
  CurrencyEntry(code: 'CHF', name: 'Swiss Franc',               symbol: 'Fr',   flag: '🇨🇭', toInrRate: 94.6),
  CurrencyEntry(code: 'CLP', name: 'Chilean Peso',              symbol: '\$',   flag: '🇨🇱', toInrRate: 0.088),
  CurrencyEntry(code: 'CNY', name: 'Chinese Yuan',              symbol: '¥',    flag: '🇨🇳', toInrRate: 11.5),
  CurrencyEntry(code: 'COP', name: 'Colombian Peso',            symbol: '\$',   flag: '🇨🇴', toInrRate: 0.020),
  CurrencyEntry(code: 'CRC', name: 'Costa Rican Colón',         symbol: '₡',    flag: '🇨🇷', toInrRate: 0.16),
  CurrencyEntry(code: 'CUP', name: 'Cuban Peso',                symbol: '\$',   flag: '🇨🇺', toInrRate: 3.5),
  CurrencyEntry(code: 'CVE', name: 'Cape Verdean Escudo',       symbol: '\$',   flag: '🇨🇻', toInrRate: 0.82),
  CurrencyEntry(code: 'CZK', name: 'Czech Koruna',              symbol: 'Kč',   flag: '🇨🇿', toInrRate: 3.7),
  CurrencyEntry(code: 'DJF', name: 'Djiboutian Franc',          symbol: 'Fr',   flag: '🇩🇯', toInrRate: 0.47),
  CurrencyEntry(code: 'DKK', name: 'Danish Krone',              symbol: 'kr',   flag: '🇩🇰', toInrRate: 12.1),
  CurrencyEntry(code: 'DOP', name: 'Dominican Peso',            symbol: '\$',   flag: '🇩🇴', toInrRate: 1.44),
  CurrencyEntry(code: 'DZD', name: 'Algerian Dinar',            symbol: 'دج',   flag: '🇩🇿', toInrRate: 0.62),
  CurrencyEntry(code: 'EGP', name: 'Egyptian Pound',            symbol: '£',    flag: '🇪🇬', toInrRate: 1.72),
  CurrencyEntry(code: 'ETB', name: 'Ethiopian Birr',            symbol: 'Br',   flag: '🇪🇹', toInrRate: 0.71),
  CurrencyEntry(code: 'EUR', name: 'Euro',                      symbol: '€',    flag: '🇪🇺', toInrRate: 91.5),
  CurrencyEntry(code: 'FJD', name: 'Fijian Dollar',             symbol: '\$',   flag: '🇫🇯', toInrRate: 37.6),
  CurrencyEntry(code: 'GBP', name: 'British Pound',             symbol: '£',    flag: '🇬🇧', toInrRate: 107.2),
  CurrencyEntry(code: 'GEL', name: 'Georgian Lari',             symbol: '₾',    flag: '🇬🇪', toInrRate: 30.3),
  CurrencyEntry(code: 'GHS', name: 'Ghanaian Cedi',             symbol: '₵',    flag: '🇬🇭', toInrRate: 5.5),
  CurrencyEntry(code: 'GMD', name: 'Gambian Dalasi',            symbol: 'D',    flag: '🇬🇲', toInrRate: 1.24),
  CurrencyEntry(code: 'GTQ', name: 'Guatemalan Quetzal',        symbol: 'Q',    flag: '🇬🇹', toInrRate: 10.8),
  CurrencyEntry(code: 'GYD', name: 'Guyanese Dollar',           symbol: '\$',   flag: '🇬🇾', toInrRate: 0.40),
  CurrencyEntry(code: 'HKD', name: 'Hong Kong Dollar',          symbol: 'HK\$', flag: '🇭🇰', toInrRate: 10.7),
  CurrencyEntry(code: 'HNL', name: 'Honduran Lempira',          symbol: 'L',    flag: '🇭🇳', toInrRate: 3.38),
  CurrencyEntry(code: 'HTG', name: 'Haitian Gourde',            symbol: 'G',    flag: '🇭🇹', toInrRate: 0.64),
  CurrencyEntry(code: 'HUF', name: 'Hungarian Forint',          symbol: 'Ft',   flag: '🇭🇺', toInrRate: 0.23),
  CurrencyEntry(code: 'IDR', name: 'Indonesian Rupiah',         symbol: 'Rp',   flag: '🇮🇩', toInrRate: 0.0053),
  CurrencyEntry(code: 'ILS', name: 'Israeli New Shekel',        symbol: '₪',    flag: '🇮🇱', toInrRate: 22.7),
  CurrencyEntry(code: 'INR', name: 'Indian Rupee',              symbol: '₹',    flag: '🇮🇳', toInrRate: 1.0),
  CurrencyEntry(code: 'IQD', name: 'Iraqi Dinar',               symbol: 'ع.د',  flag: '🇮🇶', toInrRate: 0.064),
  CurrencyEntry(code: 'IRR', name: 'Iranian Rial',              symbol: '﷼',    flag: '🇮🇷', toInrRate: 0.0020),
  CurrencyEntry(code: 'ISK', name: 'Icelandic Króna',           symbol: 'kr',   flag: '🇮🇸', toInrRate: 0.61),
  CurrencyEntry(code: 'JMD', name: 'Jamaican Dollar',           symbol: '\$',   flag: '🇯🇲', toInrRate: 0.54),
  CurrencyEntry(code: 'JOD', name: 'Jordanian Dinar',           symbol: 'د.ا',  flag: '🇯🇴', toInrRate: 117.7),
  CurrencyEntry(code: 'JPY', name: 'Japanese Yen',              symbol: '¥',    flag: '🇯🇵', toInrRate: 0.56),
  CurrencyEntry(code: 'KES', name: 'Kenyan Shilling',           symbol: 'KSh',  flag: '🇰🇪', toInrRate: 0.65),
  CurrencyEntry(code: 'KGS', name: 'Kyrgystani Som',            symbol: 'с',    flag: '🇰🇬', toInrRate: 0.96),
  CurrencyEntry(code: 'KHR', name: 'Cambodian Riel',            symbol: '៛',    flag: '🇰🇭', toInrRate: 0.021),
  CurrencyEntry(code: 'KRW', name: 'South Korean Won',          symbol: '₩',    flag: '🇰🇷', toInrRate: 0.061),
  CurrencyEntry(code: 'KWD', name: 'Kuwaiti Dinar',             symbol: 'د.ك',  flag: '🇰🇼', toInrRate: 272.5),
  CurrencyEntry(code: 'KZT', name: 'Kazakhstani Tenge',         symbol: '₸',    flag: '🇰🇿', toInrRate: 0.19),
  CurrencyEntry(code: 'LAK', name: 'Laotian Kip',               symbol: '₭',    flag: '🇱🇦', toInrRate: 0.0040),
  CurrencyEntry(code: 'LBP', name: 'Lebanese Pound',            symbol: '£',    flag: '🇱🇧', toInrRate: 0.00093),
  CurrencyEntry(code: 'LKR', name: 'Sri Lankan Rupee',          symbol: 'Rs',   flag: '🇱🇰', toInrRate: 0.28),
  CurrencyEntry(code: 'LYD', name: 'Libyan Dinar',              symbol: 'ل.د',  flag: '🇱🇾', toInrRate: 17.4),
  CurrencyEntry(code: 'MAD', name: 'Moroccan Dirham',           symbol: 'MAD',  flag: '🇲🇦', toInrRate: 8.4),
  CurrencyEntry(code: 'MDL', name: 'Moldovan Leu',              symbol: 'L',    flag: '🇲🇩', toInrRate: 4.7),
  CurrencyEntry(code: 'MKD', name: 'Macedonian Denar',          symbol: 'ден',  flag: '🇲🇰', toInrRate: 1.49),
  CurrencyEntry(code: 'MMK', name: 'Myanmar Kyat',              symbol: 'K',    flag: '🇲🇲', toInrRate: 0.040),
  CurrencyEntry(code: 'MNT', name: 'Mongolian Tögrög',          symbol: '₮',    flag: '🇲🇳', toInrRate: 0.025),
  CurrencyEntry(code: 'MOP', name: 'Macanese Pataca',           symbol: 'P',    flag: '🇲🇴', toInrRate: 10.4),
  CurrencyEntry(code: 'MUR', name: 'Mauritian Rupee',           symbol: 'Rs',   flag: '🇲🇺', toInrRate: 1.88),
  CurrencyEntry(code: 'MVR', name: 'Maldivian Rufiyaa',         symbol: 'Rf',   flag: '🇲🇻', toInrRate: 5.43),
  CurrencyEntry(code: 'MXN', name: 'Mexican Peso',              symbol: '\$',   flag: '🇲🇽', toInrRate: 4.3),
  CurrencyEntry(code: 'MYR', name: 'Malaysian Ringgit',         symbol: 'RM',   flag: '🇲🇾', toInrRate: 18.8),
  CurrencyEntry(code: 'MZN', name: 'Mozambican Metical',        symbol: 'MT',   flag: '🇲🇿', toInrRate: 1.31),
  CurrencyEntry(code: 'NAD', name: 'Namibian Dollar',           symbol: '\$',   flag: '🇳🇦', toInrRate: 4.6),
  CurrencyEntry(code: 'NGN', name: 'Nigerian Naira',            symbol: '₦',    flag: '🇳🇬', toInrRate: 0.055),
  CurrencyEntry(code: 'NIO', name: 'Nicaraguan Córdoba',        symbol: 'C\$',  flag: '🇳🇮', toInrRate: 2.3),
  CurrencyEntry(code: 'NOK', name: 'Norwegian Krone',           symbol: 'kr',   flag: '🇳🇴', toInrRate: 7.7),
  CurrencyEntry(code: 'NPR', name: 'Nepalese Rupee',            symbol: 'Rs',   flag: '🇳🇵', toInrRate: 0.63),
  CurrencyEntry(code: 'NZD', name: 'New Zealand Dollar',        symbol: 'NZ\$', flag: '🇳🇿', toInrRate: 49.3),
  CurrencyEntry(code: 'OMR', name: 'Omani Rial',                symbol: 'ر.ع.', flag: '🇴🇲', toInrRate: 217.2),
  CurrencyEntry(code: 'PAB', name: 'Panamanian Balboa',         symbol: 'B/.',  flag: '🇵🇦', toInrRate: 83.5),
  CurrencyEntry(code: 'PEN', name: 'Peruvian Sol',              symbol: 'S/.',  flag: '🇵🇪', toInrRate: 22.5),
  CurrencyEntry(code: 'PHP', name: 'Philippine Peso',           symbol: '₱',    flag: '🇵🇭', toInrRate: 1.48),
  CurrencyEntry(code: 'PKR', name: 'Pakistani Rupee',           symbol: 'Rs',   flag: '🇵🇰', toInrRate: 0.30),
  CurrencyEntry(code: 'PLN', name: 'Polish Złoty',              symbol: 'zł',   flag: '🇵🇱', toInrRate: 21.1),
  CurrencyEntry(code: 'PYG', name: 'Paraguayan Guaraní',        symbol: '₲',    flag: '🇵🇾', toInrRate: 0.011),
  CurrencyEntry(code: 'QAR', name: 'Qatari Riyal',              symbol: 'ر.ق',  flag: '🇶🇦', toInrRate: 22.9),
  CurrencyEntry(code: 'RON', name: 'Romanian Leu',              symbol: 'lei',  flag: '🇷🇴', toInrRate: 18.4),
  CurrencyEntry(code: 'RSD', name: 'Serbian Dinar',             symbol: 'din',  flag: '🇷🇸', toInrRate: 0.78),
  CurrencyEntry(code: 'RUB', name: 'Russian Ruble',             symbol: '₽',    flag: '🇷🇺', toInrRate: 0.93),
  CurrencyEntry(code: 'RWF', name: 'Rwandan Franc',             symbol: 'Fr',   flag: '🇷🇼', toInrRate: 0.063),
  CurrencyEntry(code: 'SAR', name: 'Saudi Riyal',               symbol: 'ر.س',  flag: '🇸🇦', toInrRate: 22.3),
  CurrencyEntry(code: 'SCR', name: 'Seychellois Rupee',         symbol: 'Rs',   flag: '🇸🇨', toInrRate: 6.1),
  CurrencyEntry(code: 'SDG', name: 'Sudanese Pound',            symbol: '£',    flag: '🇸🇩', toInrRate: 0.13),
  CurrencyEntry(code: 'SEK', name: 'Swedish Krona',             symbol: 'kr',   flag: '🇸🇪', toInrRate: 8.0),
  CurrencyEntry(code: 'SGD', name: 'Singapore Dollar',          symbol: 'S\$',  flag: '🇸🇬', toInrRate: 62.4),
  CurrencyEntry(code: 'SOS', name: 'Somali Shilling',           symbol: 'Sh',   flag: '🇸🇴', toInrRate: 0.15),
  CurrencyEntry(code: 'SRD', name: 'Surinamese Dollar',         symbol: '\$',   flag: '🇸🇷', toInrRate: 2.6),
  CurrencyEntry(code: 'SYP', name: 'Syrian Pound',              symbol: '£',    flag: '🇸🇾', toInrRate: 0.0065),
  CurrencyEntry(code: 'SZL', name: 'Swazi Lilangeni',           symbol: 'L',    flag: '🇸🇿', toInrRate: 4.6),
  CurrencyEntry(code: 'THB', name: 'Thai Baht',                 symbol: '฿',    flag: '🇹🇭', toInrRate: 2.3),
  CurrencyEntry(code: 'TJS', name: 'Tajikistani Somoni',        symbol: 'SM',   flag: '🇹🇯', toInrRate: 7.6),
  CurrencyEntry(code: 'TMT', name: 'Turkmenistani Manat',       symbol: 'T',    flag: '🇹🇲', toInrRate: 23.9),
  CurrencyEntry(code: 'TND', name: 'Tunisian Dinar',            symbol: 'د.ت',  flag: '🇹🇳', toInrRate: 27.2),
  CurrencyEntry(code: 'TOP', name: 'Tongan Paʻanga',            symbol: 'T\$',  flag: '🇹🇴', toInrRate: 36.6),
  CurrencyEntry(code: 'TRY', name: 'Turkish Lira',              symbol: '₺',    flag: '🇹🇷', toInrRate: 2.5),
  CurrencyEntry(code: 'TTD', name: 'Trinidad & Tobago Dollar',  symbol: '\$',   flag: '🇹🇹', toInrRate: 12.3),
  CurrencyEntry(code: 'TWD', name: 'New Taiwan Dollar',         symbol: 'NT\$', flag: '🇹🇼', toInrRate: 2.6),
  CurrencyEntry(code: 'TZS', name: 'Tanzanian Shilling',        symbol: 'Sh',   flag: '🇹🇿', toInrRate: 0.032),
  CurrencyEntry(code: 'UAH', name: 'Ukrainian Hryvnia',         symbol: '₴',    flag: '🇺🇦', toInrRate: 2.0),
  CurrencyEntry(code: 'UGX', name: 'Ugandan Shilling',          symbol: 'Sh',   flag: '🇺🇬', toInrRate: 0.022),
  CurrencyEntry(code: 'USD', name: 'US Dollar',                 symbol: '\$',   flag: '🇺🇸', toInrRate: 83.5),
  CurrencyEntry(code: 'UYU', name: 'Uruguayan Peso',            symbol: '\$',   flag: '🇺🇾', toInrRate: 2.1),
  CurrencyEntry(code: 'UZS', name: 'Uzbekistani Som',           symbol: "so'm", flag: '🇺🇿', toInrRate: 0.0066),
  CurrencyEntry(code: 'VES', name: 'Venezuelan Bolívar',        symbol: 'Bs.S', flag: '🇻🇪', toInrRate: 2.3),
  CurrencyEntry(code: 'VND', name: 'Vietnamese Dong',           symbol: '₫',    flag: '🇻🇳', toInrRate: 0.0034),
  CurrencyEntry(code: 'WST', name: 'Samoan Tālā',               symbol: 'T',    flag: '🇼🇸', toInrRate: 31.3),
  CurrencyEntry(code: 'XAF', name: 'Central African CFA Franc', symbol: 'Fr',   flag: '🇨🇲', toInrRate: 0.14),
  CurrencyEntry(code: 'XCD', name: 'East Caribbean Dollar',     symbol: '\$',   flag: '🇦🇬', toInrRate: 30.9),
  CurrencyEntry(code: 'XOF', name: 'West African CFA Franc',    symbol: 'Fr',   flag: '🇸🇳', toInrRate: 0.14),
  CurrencyEntry(code: 'YER', name: 'Yemeni Rial',               symbol: '﷼',    flag: '🇾🇪', toInrRate: 0.33),
  CurrencyEntry(code: 'ZAR', name: 'South African Rand',        symbol: 'R',    flag: '🇿🇦', toInrRate: 4.6),
  CurrencyEntry(code: 'ZMW', name: 'Zambian Kwacha',            symbol: 'ZK',   flag: '🇿🇲', toInrRate: 3.1),
];
